### ISSUE TITLE
Flags enum doesn't pass the IsDefined Check

### ISSUE THREAD

**Issue by NickAcPT** [peteroupc/CBOR#42]
A Flags enum will never pass an IsDefined check.
Problem is in `PeterO.Cbor.PropertyMap.ObjectToEnum`
<details>
<summary>Stacktrace</summary>

```
PeterO.Cbor.CBORException: Unrecognized enum value: 4161
   at PeterO.Cbor.PropertyMap.ObjectToEnum(CBORObject obj, Type enumType)
   at PeterO.Cbor.PropertyMap.TypeToObject(CBORObject objThis, Type t, CBORTypeMapper mapper, PODOptions options, Int32 depth)
   at PeterO.Cbor.CBORObject.ToObject(Type t, CBORTypeMapper mapper, PODOptions options, Int32 depth)
   at PeterO.Cbor.PropertyMap.ObjectWithProperties(Type t, IEnumerable`1 keysValues, CBORTypeMapper mapper, PODOptions options, Int32 depth)
```

</details>

[This](https://stackoverflow.com/a/8828483/12027881) could be a way to fix it.

edit: cc: @peteroupc

**Comment by peteroupc** [comment]
Fixed in 491aa10.
