### ISSUE TITLE
Could not load file or assembly 'Numbers'

### ISSUE THREAD

**Issue by charlesroddie** [peteroupc/CBOR#45]
Error from PeterO.Cbor 4.1.1.
```
Could not load file or assembly 'Numbers, Version=1.6.0.0, Culture=neutral, PublicKeyToken=9cd62db60ea5554c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at PeterO.Cbor.CBORObject.WriteTo(Stream stream, CBOREncodeOptions options)
   at PeterO.Cbor.CBORObject.EncodeToBytes(CBOREncodeOptions options)
```

4.1.0 is OK.

This is tested in a UWP project.

**Comment by peteroupc** [comment]
Version 4.1.2 was just pushed.  It might address this issue.

**Comment by charlesroddie** [comment]
Yes it seems to fix the problem.
