### ISSUE TITLE
CBORObject.Write() incorrectly serializes certain floats / Single values

### ISSUE THREAD

**Issue by sdellenb** [peteroupc/CBOR#80]
We ran into an issue where a Single value of `float.Epsilon` is incorrectly serialized.

To replicate it, I changed `TestWriteExtra()` as follows (replaced `0.0f` with `float.Epsilon`)

```diff
git diff
diff --git a/CBORTest/CBORObjectTest.cs b/CBORTest/CBORObjectTest.cs
index 9197ba27..cfdb4e87 100644
--- a/CBORTest/CBORObjectTest.cs
+++ b/CBORTest/CBORObjectTest.cs
@@ -6975,11 +6975,11 @@ public void TestWriteExtra() {
           TestWriteExtraOne(values[i]);
         }
         {
-          CBORObject cborTemp1 = ToObjectTest.TestToFromObjectRoundTrip(0.0f);
-          CBORObject cborTemp2 = ToObjectTest.TestToFromObjectRoundTrip(0.0f);
+          CBORObject cborTemp1 = ToObjectTest.TestToFromObjectRoundTrip(float.Epsilon);
+          CBORObject cborTemp2 = ToObjectTest.TestToFromObjectRoundTrip(float.Epsilon);
           TestCommon.CompareTestEqualAndConsistent(cborTemp1, cborTemp2);
           try {
-            CBORObject.Write(0.0f, null);
+            CBORObject.Write(float.Epsilon, null);
             Assert.Fail("Should have failed");
           } catch (ArgumentNullException) {
             // NOTE: Intentionally empty
@@ -6989,14 +6989,14 @@ public void TestWriteExtra() {
           }
           AssertWriteThrow(cborTemp1);
           using (var ms = new Test.DelayingStream()) {
-            CBORObject.Write(0.0f, ms);
+            CBORObject.Write(float.Epsilon, ms);
             CBORObject.Write(cborTemp1, ms);
             cborTemp1.WriteTo(ms);
             AssertReadThree(
               ms.ToArray(),
-              ToObjectTest.TestToFromObjectRoundTrip(0.0f));
+              ToObjectTest.TestToFromObjectRoundTrip(float.Epsilon));
           }
-          TestWriteObj(0.0f, 0.0f);
+          TestWriteObj(float.Epsilon, float.Epsilon);
         }
```

The test then fails with

```
dotnet test --filter Name="TestWriteExtra"
  Determining projects to restore...
  All projects are up-to-date for restore.
  CBOR -> C:\git\github.com\PeterO.Cbor\CBOR\bin\Debug\netstandard1.0\CBOR.dll
  CBOR -> C:\git\github.com\PeterO.Cbor\CBOR\bin\Debug\net6.0\CBOR.dll
  CBORTest -> C:\git\github.com\PeterO.Cbor\CBORTest\bin\Debug\netcoreapp8.0\CBORTest.dll
Test run for C:\git\github.com\PeterO.Cbor\CBORTest\bin\Debug\netcoreapp8.0\CBORTest.dll (.NETCoreApp,Version=v8.0)
VSTest version 17.11.0 (x64)

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestWriteExtra [158 ms]
  Error Message:
   Multiple failures or warnings in test:
  1) Not equal: -1:
1 and
1.401298464324817E-45
  2) NUnit.Framework.AssertionException: Not equal: -1:
1 and
1.401298464324817E-45
   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at NUnit.Framework.Assert.Fail(String message)
   at Test.TestCommon.CompareTestEqualAndConsistent[T](T o1, T o2, String msg) in C:\git\github.com\PeterO.Cbor\CBORTest\TestCommon.cs:line 321
   at Test.TestCommon.CompareTestEqualAndConsistent[T](T o1, T o2) in C:\git\github.com\PeterO.Cbor\CBORTest\TestCommon.cs:line 310
   at Test.CBORObjectTest.AssertReadThree(Byte[] bytes, CBORObject cbor) in C:\git\github.com\PeterO.Cbor\CBORTest\CBORObjectTest.cs:line 7516
new byte[] { (byte)0xF9,0x3C,0x00,(byte)0xFA,0x00,0x00,0x00,0x01,(byte)0xFA,0x00,0x00,0x00,0x01}
cbor = 1.401298464324817E-45


  Stack Trace:
     at Test.CBORObjectTest.AssertReadThree(Byte[] bytes, CBORObject cbor) in C:\git\github.com\PeterO.Cbor\CBORTest\CBORObjectTest.cs:line 7522
   at Test.CBORObjectTest.TestWriteExtra() in C:\git\github.com\PeterO.Cbor\CBORTest\CBORObjectTest.cs:line 6995


Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 158 ms - CBORTest.dll (net8.0)
```

When serializing an array of floats, the issue does not occur, as `CBORObject.Add()` internally uses `CBORObject.FromObject()`.

A workaround is to change

```csharp
        CBORObject.Write(float.Epsilon, stream);
```
to
```csharp
        CBORObject.Write(CBORObject.FromObject(float.Epsilon), stream);
```

**Comment by peteroupc** [comment]
Solved.
